ignorePatterns: ['node_modules/']

env:
  es6: true
  node: true

settings:
  import/parsers:
    '@typescript-eslint/parser': [.ts, .tsx]
  import/resolver:
    node:
      extensions: [.ts, .tsx]

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  project: ./tsconfig.json

extends:
  - airbnb-typescript/base
  - plugin:@typescript-eslint/recommended
  - prettier

plugins:
  - simple-import-sort
  - import
  - unused-imports
  - '@typescript-eslint'
  - prettier

rules:
  '@typescript-eslint/explicit-function-return-type': 0
  '@typescript-eslint/no-explicit-any': 0
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  no-console: 0
  no-param-reassign: 0
  prettier/prettier: 2
  '@typescript-eslint/explicit-module-boundary-types': 0
  import/extensions: 0
  simple-import-sort/imports: 2
  simple-import-sort/exports: 2
  import/first: 2
  import/newline-after-import: 2
  import/no-duplicates: 2
  unused-imports/no-unused-imports: 2

globals:
  BigInt: true
