ignorePatterns: ['node_modules/']

env:
  es6: true
  node: true

parserOptions:
  ecmaVersion: 2018
  sourceType: module

extends:
  - prettier

plugins:
  - simple-import-sort
  - import
  - unused-imports
  - prettier

rules:
  import/no-extraneous-dependencies: 0
  import/prefer-default-export: 0
  no-console: 0
  no-param-reassign: 0
  prettier/prettier: 2
  import/extensions: 0
  simple-import-sort/imports: 2
  simple-import-sort/exports: 2
  import/first: 2
  import/newline-after-import: 2
  import/no-duplicates: 2
  unused-imports/no-unused-imports: 2
  no-underscore-dangle: 0

globals:
  BigInt: true

overrides:
  - files: ['**/*.ts']
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: 2018
      sourceType: module
      project: ./tsconfig.json
    extends:
      - airbnb-typescript/base
      - plugin:@typescript-eslint/recommended
      - prettier
    settings:
      import/parsers:
        '@typescript-eslint/parser': [.ts, .tsx]
      import/resolver:
        node:
          extensions: [.ts, .tsx]
    plugins:
      - simple-import-sort
      - import
      - unused-imports
      - prettier
      - '@typescript-eslint'
    rules:
      import/no-extraneous-dependencies: 0
      import/prefer-default-export: 0
      no-console: 0
      no-param-reassign: 0
      prettier/prettier: 2
      import/extensions: 0
      simple-import-sort/imports: 2
      simple-import-sort/exports: 2
      import/first: 2
      import/newline-after-import: 2
      import/no-duplicates: 2
      unused-imports/no-unused-imports: 2
      no-underscore-dangle: 0
      '@typescript-eslint/explicit-function-return-type': 0
      '@typescript-eslint/no-explicit-any': 0
      '@typescript-eslint/explicit-module-boundary-types': 0
