runs:
  using: composite

  steps:
    - name: Install dependencies
      shell: bash
      run: |
        rm -rf l packages/vscode-slonik-live-server/node_modules
        yarn --immutable

    - name: Build
      shell: bash
      run: yarn build

    - name: Check linting
      shell: bash
      run: yarn lint

    - name: Check types
      shell: bash
      run: yarn types

    - name: Run tests
      shell: bash
      run: yarn test:ci

    - name: Check vsce package deps
      shell: bash
      run: |
        cd packages/vscode-slonik-live-server
        rm -rf node_modules && yarn --immutable
        VSCE_DEPS="$(yarn vsce ls)"
        CHECK="node_modules/ts-slonik-live-server-plugin"
        [[ "$VSCE_DEPS" =~ "$CHECK" ]] || (echo "ERROR: missing $CHECK" && exit 1)
        CHECK='node_modules/ts-slonik-live-server-plugin/node_modules/slonik/package.json'
        [[ "$VSCE_DEPS" =~ "$CHECK" ]] || (echo "ERROR: missing $CHECK" && exit 1)
