name: Pull request status checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  status-checks:
    name: Run status checks

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 54321:5432
        env:
          POSTGRES_PASSWORD: secretpassword

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run status checks
        uses: ./.github/workflows/status-checks
