name: Release

on:
  push:
    branches: [main]

jobs:
  status-checks:
    name: Run status checks and release

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 54321:5432
        env:
          POSTGRES_PASSWORD: secretpassword

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            .yarn/cache
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Run status checks
        uses: ./.github/workflows/status-checks

      - name: Release
        run: |
          rm -rf packages/vscode-slonik-live-server/node_modules
          yarn --immutable
          yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
